/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DesignButton {
        "appearance": string;
        "text": string;
    }
    interface DesignModal {
        "appearance": string;
        "buttons": string;
        "closeIcon": string;
        "header": string;
        "isOpen": boolean;
    }
    interface GridAreas {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface DesignModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDesignModalElement;
}
declare global {
    interface HTMLDesignButtonElement extends Components.DesignButton, HTMLStencilElement {
    }
    var HTMLDesignButtonElement: {
        prototype: HTMLDesignButtonElement;
        new (): HTMLDesignButtonElement;
    };
    interface HTMLDesignModalElement extends Components.DesignModal, HTMLStencilElement {
    }
    var HTMLDesignModalElement: {
        prototype: HTMLDesignModalElement;
        new (): HTMLDesignModalElement;
    };
    interface HTMLGridAreasElement extends Components.GridAreas, HTMLStencilElement {
    }
    var HTMLGridAreasElement: {
        prototype: HTMLGridAreasElement;
        new (): HTMLGridAreasElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "design-button": HTMLDesignButtonElement;
        "design-modal": HTMLDesignModalElement;
        "grid-areas": HTMLGridAreasElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface DesignButton {
        "appearance"?: string;
        "text"?: string;
    }
    interface DesignModal {
        "appearance"?: string;
        "buttons"?: string;
        "closeIcon"?: string;
        "header"?: string;
        "isOpen"?: boolean;
        "onAction"?: (event: DesignModalCustomEvent<any>) => void;
    }
    interface GridAreas {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "design-button": DesignButton;
        "design-modal": DesignModal;
        "grid-areas": GridAreas;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "design-button": LocalJSX.DesignButton & JSXBase.HTMLAttributes<HTMLDesignButtonElement>;
            "design-modal": LocalJSX.DesignModal & JSXBase.HTMLAttributes<HTMLDesignModalElement>;
            "grid-areas": LocalJSX.GridAreas & JSXBase.HTMLAttributes<HTMLGridAreasElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
